### ISSUE TITLE
"Give an option to not connect offline Discord users" - Bug

### ISSUE THREAD

**Issue by Untouched6338** [PyLink/pylink-discord#18]
Setting Discord status to "Do Not Disturb" causes the IRC user to quit
and not respawn regardless of what status is set to.

It said I went offline when I didn't

**Comment by jlu5** [comment]
I can't reproduce this - do you see any errors in the console or the PyLink logs?

**Comment by Untouched6338** [comment]
@jlu5 I have found a possible cause of this.
On Discord set your status to invisible, change your nick and then set status to online.

**Comment by totalsecond** [comment]
> On Discord set your status to invisible, change your nick and then set status to online.

I can reproduce.

**Comment by jlu5** [comment]
OK, my guess is that this is the same problem caused by #19
